#!/bin/bash
set -e

out_dir=$(pwd -P)
repo_dir=${1:-$out_dir}

[[ -n $DEB_PACKAGE ]]
[[ -n $DEB_VERSION ]]
[[ -n $DEB_SHA256 ]]
[[ -n $SOURCE_DATE_EPOCH ]]
[[ -n $DPKG_DEB_COMPRESSOR_TYPE ]]

declare -x SOURCE_DATE_EPOCH DPKG_DEB_COMPRESSOR_TYPE

tmp_deb=$(mktemp "$DEB_PACKAGE"_XXXXXX.deb)
dpkg-deb --build --root-owner-group "$repo_dir/$DEB_PACKAGE" "$tmp_deb"

read -r deb_package deb_version <<< "$(
    dpkg-deb --show --showformat='${Package} ${Version}\n' \
        "$tmp_deb"
)"

[[ $DEB_PACKAGE == "$deb_package" ]]
[[ $DEB_VERSION == "$deb_version" ]]

deb_fname="${deb_package}_${deb_version}.deb"
mv -v "$tmp_deb" "$out_dir/$deb_fname"

sha256sum --check <<< "$DEB_SHA256  $out_dir/$deb_fname"

tee "$out_dir/check-build-simple.out" >&2 << EOF
CHECK_BUILD=pass
EOF
