#!/bin/bash

source "${BASH_SOURCE[0]%/*}"/util && init || exit 255

out_dir=$(pwd -P)
repo_dir=${1:-$out_dir}
repo_url=${2:?}

req_repo "$repo_url" "$repo_dir"
req_permsrc "$repo_dir"
req_buildmeta "$repo_dir"
