#!/bin/bash

source "${BASH_SOURCE[0]%/*}"/util && init || exit 255

out_dir=$(pwd -P)

[[ $CHECK_BUILD == "pass" ]]

tee -a "$out_dir/report.out" >&2 << EOF
## Build reproducibility confirmed

### Package
*$DEB_PACKAGE*

### Version
*$DEB_VERSION*

### Checksum SHA256

$DEB_SHA256
EOF

[[ $CHECK_URL == "pass" ]]

tee -a "$out_dir/report.out" >&2 << EOF

## Published package checksum verified

### URL
[$DEB_URL]($DEB_URL)

*$CHECK_URL_LAST* Checksum matches that of the reproduced build.
EOF
