name: Build Repo
on:
  workflow_call:
    inputs:
      repo_url:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        run: git clone ${{ inputs.repo_url }}
      - name: Build package
        run: |
          cd $(basename ${{ inputs.repo_url }} .git)
          ls -la
