#!/bin/bash

init() {
    trap 'echo "${BASH_SOURCE[0]##*/}: Error $? (l.$LINENO) - aborted."; exit 1;' ERR
}

req_permsrc() {
    [[ -n $1 ]] && declare repo_dir=$1 || return 255

    (cd "$repo_dir" && source .permsrc || exit 1)
}

req_buildmeta() {
    [[ -n $1 ]] && declare search_dir=$1 || return 255

    found_buildmeta=("$search_dir"/*.buildmeta)
    ((${#found_buildmeta[@]} == 1))
    buildmeta=${found_buildmeta[0]}
    [[ -f $buildmeta ]]
    buildmeta_fname=${buildmeta##*/}

    target="${buildmeta_fname%%.buildmeta}"
    package=${target%%_*}
    version=${target#*_}

    source "$buildmeta" || return 255

    tee "buildmeta.out" >&2 << EOF
DEB_PACKAGE=$package
DEB_VERSION=$version

SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH
DPKG_DEB_COMPRESSOR_TYPE=$DPKG_DEB_COMPRESSOR_TYPE

DEB_SHA256=$DEB_SHA256
DEB_URL=$DEB_URL
EOF
}
