name: "[Build image]"

on:
  workflow_call:
    inputs:
      git-url:
        required: true
        type: string
      git-ref:
        required: false
        type: string
        default: main
      def-name:
        required: true
        type: string
      image-name:
        required: true
        type: string
      image-tag:
        required: false
        type: string
        default: latest

defaults:
  run:
    shell: bash

env:
  GIT_URL: ${{ inputs.git-url }}
  GIT_REF: ${{ inputs.git-ref }}
  BUILD_SCRIPT: def/${{ inputs.def-name }}/build
  BOOTSTRAP_YAML: def/${{ inputs.def-name }}/bootstrap.yaml
  CR_URL: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: ${{ inputs.image-name }}
  IMAGE_TAG: ${{ inputs.image-tag }}

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Prep runner toolset
        uses: disputechalice/test-gh-actions/apt-satisfy@main
        with:
          expression: >
            debian-archive-keyring
            bdebstrap
            buildah
            podman

      - id: def
        name: Fetch def tree
        uses: disputechalice/test-gh-actions/tree-from-gitref@main
        with:
          git-url: ${{ env.GIT_URL }}
          git-ref: ${{ env.GIT_REF }}
          target: def

      - id: build
        name: Build image
        env:
          SOURCE_DATE_EPOCH: ${{ steps.def.outputs.git-commit-epoch }}
          IMAGE_SOURCE: ${{ inputs.git-url }}
          IMAGE_REVISION: ${{ steps.def.outputs.git-commit }}

        run: |
          exec 3> >(tee -a "$GITHUB_OUTPUT" >&2)

          export SOURCE_DATE_EPOCH IMAGE_{NAME,SOURCE,REVISION}

          buildah unshare "$BUILD_SCRIPT"

          cat "$IMAGE_NAME/manifest" || ls -laR

          cat >&3 << EOF
          rootfs-diffids=$(buildah inspect "$IMAGE_NAME" | jq -c '.OCIv1.rootfs.diff_ids')
          EOF

      - name: Check image
        run: |
          source <(podman run --pull=never "$IMAGE_NAME" cat /etc/os-release)
          [[ $ID == debian ]]

      - id: push
        name: Push to Registry
        env:
          RUN_ID: ${{ github.run_id }}
        run: |
          exec 3> >(tee -a "$GITHUB_OUTPUT" >&2)

          buildah login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"

          push_name="$CR_URL/$IMAGE_NAME"

          buildah tag "$IMAGE_NAME" "$push_name:$IMAGE_TAG"

          buildah push \
            --digestfile digestfile \
            "$push_name:$IMAGE_TAG"

          tagged="$push_name:r-$RUN_ID"
          buildah tag "$IMAGE_NAME" "$tagged"
          buildah push "$tagged"

          cat >&3 << EOF
          image-pushed-name=$push_name
          image-digest=$(cat digestfile)
          EOF

      - name: Summarize
        env:
          ROOTFS_DIFFID0: ${{ fromJSON(steps.build.outputs.rootfs-diffids)[0] }}
          IMAGE_PUSHED_NAME: ${{ steps.push.outputs.image-pushed-name }}
          IMAGE_PUSHED_DIGEST: ${{ steps.push.outputs.image-digest }}
          GIT_COMMIT: ${{ steps.def.outputs.git-commit }}
          TAR_SHA256: ${{ steps.def.outputs.tar-sha256 }}
        run: |
          exec 4> >(tee -a "$GITHUB_STEP_SUMMARY" >&2)
          
          # Build markdown summary
          trap 'echo >&2 E$? L$LINENO' ERR
          : "${IMAGE_PUSHED_DIGEST:?}"

          tee -a "report.md" >&2 << EOF
          $IMAGE_PUSHED_NAME : $IMAGE_TAG

          rootfs diffid 0: ${ROOTFS_DIFFID0#*:}

          pushed image: $IMAGE_PUSHED_DIGEST

          \`\`\`
          $(yq '.mmdebstrap.suite' "$BOOTSTRAP_YAML")
          $(yq '.mmdebstrap.variant' "$BOOTSTRAP_YAML")
          $(yq '.mmdebstrap.mirrors' "$BOOTSTRAP_YAML")
          \`\`\`

          Image def:
          - from commit $GIT_COMMIT
          - tarball SHA256: $TAR_SHA256
          EOF

          cat report.md >&4
