name: "[Build image]"

on:
  workflow_call:
    inputs:
      git-repo:
        description: "Git repository containing the image definition(s)"
        required: true
        type: string
      git-ref:
        description: "Git reference"
        required: false
        default: 'main'
        type: string
      def-name:
        description: Definition name for the image
        required: true
        type: string
      image-name:
        description: Base name of the image
        required: true
        type: string
      image-tags:
        description: Space-separated list of tags
        required: false
        default: 'latest'
        type: string

defaults:
  run:
    shell: bash

env:
  GIT_REPO: ${{ inputs.git-repo }}
  GIT_REF: ${{ inputs.git-ref }}
  IMAGE_NAME: ${{ inputs.image-name }}
  IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/${{ inputs.image-name }}
  IMAGE_TAGS: ${{ inputs.image-tags }}

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-repo: ${{ steps.push.outputs.image-repo }}
      image-digest: ${{ steps.push.outputs.image-digest }}
      rootfs-diffids: ${{ steps.build.outputs.rootfs-diffids }}
      git-commit: ${{ steps.def.outputs.git-commit }}

    steps:
      - name: Prep runner toolset
        uses: disputechalice/actions/apt-satisfy@main
        with:
          expression: >
            debian-archive-keyring
            bdebstrap
            buildah
            podman

      - id: def
        name: Fetch definitions tree
        uses: disputechalice/actions/git-archive@main
        with:
          git-repo: ${{ env.GIT_REPO }}
          git-ref: ${{ env.GIT_REF }}
          extract: true

      - id: build
        name: Build image
        env:
          SOURCE_DATE_EPOCH: ${{ steps.def.outputs.git-commit-epoch }}
          IMAGE_SOURCE: ${{ inputs.git-repo }}
          IMAGE_REVISION: ${{ steps.def.outputs.git-commit }}
          BUILD: ${{ steps.def.outputs.path }}/${{ inputs.def-name }}/build
        run: |
          export SOURCE_DATE_EPOCH IMAGE_{NAME,SOURCE,REVISION}

          buildah unshare "$BUILD"

          >&2 echo "-- OUTPUT"
          >&2 tee -a "$GITHUB_OUTPUT" << EOF
          rootfs-diffids=$(buildah inspect "$IMAGE_NAME" | jq -c '.OCIv1.rootfs.diff_ids')
          EOF

      - name: Check image
        env:
          BS_YAML: ${{ steps.def.outputs.path }}/${{ inputs.def-name }}/bootstrap.yaml
        run: |
          cat >&2 << EOF
          $(yq '.mmdebstrap.suite' "$BS_YAML")
          $(yq '.mmdebstrap.variant' "$BS_YAML")
          $(yq '.mmdebstrap.mirrors' "$BS_YAML")
          EOF
          cat "$IMAGE_NAME/manifest" >&2

          cp "$BS_YAML" "$IMAGE_NAME"

          source <(podman run --pull=never "$IMAGE_NAME" cat /etc/os-release)
          [[ $ID == debian ]]

      - id: manifest
        name: Archive manifest
        uses: disputechalice/actions/archive@main
        with:
          path: ${{ env.IMAGE_NAME }}
          base-name: ${{ env.IMAGE_NAME }}-manifest

      - id: push
        name: Push to Registry
        run: |
          : "${IMAGE_NAME:?} ${IMAGE_REPO:?} ${IMAGE_TAGS:?}"

          buildah login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"

          IFS=' ' read -ra tags <<< "$IMAGE_TAGS"
          for tag in "${tags[@]}"; do
            buildah tag "$IMAGE_NAME" "$IMAGE_REPO:$tag"
            buildah push --digestfile digest "$IMAGE_REPO:$tag"
            echo "Pushed with tag: $tag"
          done

          >&2 echo "-- OUTPUT"
          >&2 tee -a "$GITHUB_OUTPUT" << EOF
          image-repo=$IMAGE_REPO
          image-digest=$(cat digest)
          EOF

  report:
    needs: image  
    runs-on: ubuntu-latest

    steps:
      - name: Summarize
        env:
          IMAGE_REPO: ${{ needs.image.outputs.image-repo }}
          IMAGE_DIGEST: ${{ needs.image.outputs.image-digest }}
          ROOTFS_DIFFIDS: ${{ needs.image.outputs.rootfs-diffids }}
          GIT_COMMIT: ${{ needs.image.outputs.git-commit }}
        run: |
          # Build markdown summary
          trap 'echo >&2 E$? L$LINENO' ERR
          : "${IMAGE_DIGEST:?}"

          REPORT="$(mktemp /tmp/report.XXXXXX.md)"

          cat >> "$REPORT" << EOF

          $IMAGE_REPO
          $IMAGE_TAGS

          ## RootFS Diff IDs:
          $(echo "$ROOTFS_DIFFIDS" | jq -r '.[]')

          pushed image: $IMAGE_DIGEST

          Image def from:
          - $GIT_REPO
          - $GIT_REF          
          - $GIT_COMMIT

          EOF

          >&2 tee -a "$GITHUB_STEP_SUMMARY" < "$REPORT"
