name: "[Check plain package]"

on:
  workflow_call:
    inputs:
      git-repo:
        required: true
        type: string
      git-ref:
        required: true
        type: string
      package:
        required: false
        type: string
        default: ''

defaults:
  run:
    shell: bash

jobs:

  prep:
    runs-on: ubuntu-latest

    env:
      GIT_REPO: ${{ inputs.git-repo }}
      GIT_REF: ${{ inputs.git-ref }}
      PACKAGE: ${{ inputs.package }}

    outputs:
      source-artifact: ${{ steps.source.outputs.artifact }}
      env-json: ${{ steps.context.outputs.env-json }}
      prov-json: ${{ steps.context.outputs.prov-json }}      

    steps:
      - id: source
        name: Obtain source archive, extract to ingest metadata
        uses: disputechalice/actions/git-archive@main
        with:
          git-repo: ${{ env.GIT_REPO }}
          git-ref: ${{ env.GIT_REF }}
          extract: true

      - id: buildmeta-acq
        name: Acquire buildmeta file
        env:
          TARGET: ${{ steps.source.outputs.path }}
        run: |
          # Identify .buildmeta file in the source, infer target package name/version
          # Ensure single file only (per package, if specified)
          trap 'echo >&2 E$? L$LINENO' ERR
          : "${TARGET:?}"

          prefix="$TARGET/${PACKAGE:+$PACKAGE}"
          found=("$prefix"*.buildmeta)        
          ((${#found[@]} == 1))

          buildmeta_path=${found[0]}
          test -f "$buildmeta_path"

          buildmeta_filename=${buildmeta_path##*/}
          buildmeta_barename="${buildmeta_filename%%.buildmeta}"

          tee -a "$GITHUB_OUTPUT" >&2 << EOF
          path=$buildmeta_path
          package=${buildmeta_barename%%_*}
          version=${buildmeta_barename#*_}
          EOF

      - id: buildmeta-var
        name: Process buildmeta variables
        uses: disputechalice/actions/env-to-json@main
        with:
          source-file: ${{ steps.buildmeta-acq.outputs.path }}
          variable-names: SOURCE_DATE_EPOCH DPKG_DEB_COMPRESSOR_TYPE DEB_SHA256 DEB_URL

      - id: context
        name: Resolve build context
        env:
          GIT_COMMIT: ${{ steps.source.outputs.git-commit }}
          DEB_PACKAGE: ${{ steps.buildmeta-acq.outputs.package }}
          DEB_VERSION: ${{ steps.buildmeta-acq.outputs.version }}
          BUILDMETA: ${{ steps.buildmeta-var.outputs.json }}
        run: |
          # Split build-environment and provenance data as JSON
          trap 'echo >&2 E$? L$LINENO' ERR
          : "${GIT_COMMIT:?}" "${DEB_PACKAGE:?}" "${DEB_VERSION:?}" "${BUILDMETA:?}"

          env_json=$(jq -c \
            '{
              source_date_epoch,
              dpkg_deb_compressor_type
            }' <<< "$BUILDMETA")

          prov_json=$(jq -c \
            --arg git_url "$GIT_REPO" \
            --arg git_commit "$GIT_COMMIT" \
            --arg deb_package "$DEB_PACKAGE" \
            --arg deb_version "$DEB_VERSION" \
            '{
              git_url: $git_url,              
              git_commit: $git_commit,
              deb_package: $deb_package,
              deb_version: $deb_version,
              deb_sha256,
              deb_url
          }' <<< "$BUILDMETA")

          tee -a "$GITHUB_OUTPUT" >&2 << EOF
          env-json=$env_json
          prov-json=$prov_json
          EOF

  repro:  
    needs: prep
    runs-on: ubuntu-latest
    container: ghcr.io/disputechalice/builder-plain:latest

    env:
      DEB_PACKAGE: ${{ fromJson(needs.prep.outputs.prov-json).deb_package }}
      DEB_VERSION: ${{ fromJson(needs.prep.outputs.prov-json).deb_version }}
      DEB_SHA256: ${{ fromJson(needs.prep.outputs.prov-json).deb_sha256 }}
      SOURCE_DATE_EPOCH: ${{ fromJson(needs.prep.outputs.env-json).source_date_epoch }}
      DPKG_DEB_COMPRESSOR_TYPE: ${{ fromJson(needs.prep.outputs.env-json).dpkg_deb_compressor_type }}

    outputs:
      status: ${{ steps.check.outputs.status }}

    steps:
      - id: payload
        name: Get package payload
        uses: disputechalice/actions/unarchive@main
        with:
          artifact: ${{ needs.prep.outputs.source-artifact }}

      - id: check
        name: Check self-built repro package
        env:
          SOURCE_DIR: ${{ steps.payload.outputs.path }}
        run: |
          # Build package from source, verify correct name/version/checksum
          trap 'echo >&2 E$? L$LINENO' ERR
          : "${SOURCE_DIR:?} ${DEB_PACKAGE:?} ${DEB_VERSION:?} ${DEB_SHA256:?}"
          : "${SOURCE_DATE_EPOCH:?} ${DPKG_DEB_COMPRESSOR_TYPE:?}"

          built_deb=$(mktemp /tmp/repro.XXXXXX.deb)
          export SOURCE_DATE_EPOCH DPKG_DEB_COMPRESSOR_TYPE
          dpkg-deb --build --root-owner-group "$SOURCE_DIR/$DEB_PACKAGE" "$built_deb"

          dpkg-deb --contents "$built_deb"

          built="$(dpkg-deb --show --showformat='${Package}|${Version}' "$built_deb")"
          [[ "$built" == "$DEB_PACKAGE|$DEB_VERSION" ]]

          sha256sum --check <<< "$DEB_SHA256  $built_deb"

          tee -a "$GITHUB_OUTPUT" >&2 << EOF
          status=pass
          EOF

  dist:
    needs: prep
    runs-on: ubuntu-latest

    env:
      DEB_PACKAGE: ${{ fromJson(needs.prep.outputs.prov-json).deb_package }}
      DEB_VERSION: ${{ fromJson(needs.prep.outputs.prov-json).deb_version }}
      DEB_SHA256: ${{ fromJson(needs.prep.outputs.prov-json).deb_sha256 }}
      DEB_URL: ${{ fromJson(needs.prep.outputs.prov-json).deb_url }}

    outputs:
      status: ${{ steps.check.outputs.status }}

    steps:
      - id: check
        name: Check retrieved dist package
        run: |
          # Retrieve package from URL, verify correct name/version/checksum
          trap 'echo >&2 E$? L$LINENO' ERR
          : "${DEB_PACKAGE:?} ${DEB_VERSION:?} ${DEB_SHA256:?} ${DEB_URL:?}"

          dist_deb=$(mktemp /tmp/dist.XXXXXX.deb)
          wget --no-verbose -O "$dist_deb" "$DEB_URL"

          dist="$(dpkg-deb --show --showformat='${Package}|${Version}' "$dist_deb")"
          [[ "$dist" == "$DEB_PACKAGE|$DEB_VERSION" ]]

          sha256sum --check <<< "$DEB_SHA256  $dist_deb"

          tee -a "$GITHUB_OUTPUT" >&2 << EOF
          status=pass
          EOF

  report:
    needs: [prep, repro, dist]
    runs-on: ubuntu-latest

    env:
      GIT_URL: ${{ fromJson(needs.prep.outputs.prov-json).git_url }}
      GIT_COMMIT: ${{ fromJson(needs.prep.outputs.prov-json).git_commit }}
      DEB_PACKAGE: ${{ fromJson(needs.prep.outputs.prov-json).deb_package }}
      DEB_VERSION: ${{ fromJson(needs.prep.outputs.prov-json).deb_version }}
      DEB_URL: ${{ fromJson(needs.prep.outputs.prov-json).deb_url }}
      DEB_SHA256: ${{ fromJson(needs.prep.outputs.prov-json).deb_sha256 }}
      STATUS_REPRO: ${{ needs.repro.outputs.status }}
      STATUS_DIST: ${{ needs.dist.outputs.status }}

    steps:
      - name: Report summary
        run: |
          # Build markdown summary, fail overall on any single fail
          trap 'echo >&2 E$? L$LINENO' ERR
          : "${GIT_URL:?} ${GIT_COMMIT:?}"           
          : "${DEB_PACKAGE:?} ${DEB_VERSION:?} ${DEB_URL:?} ${DEB_SHA256:?}"

          REPORT="$(mktemp /tmp/report.XXXXXX.md)"

          cat >> "$REPORT" << EOF

          # Report
          As of: **$(date --rfc-3339=seconds --utc)**

          | Package | *$DEB_PACKAGE* |
          |---------|----------------|
          | Version | *$DEB_VERSION* |
          EOF

          cat >> "$REPORT" << EOF

          ## Reproducible build

          | Verified          | ${STATUS_REPRO:-fail} |
          |-------------------|-----------------------|
          | Package checksum  | $DEB_SHA256           |          
          | Source Git URL    | [$GIT_URL]($GIT_URL)  |
          | Source Git commit | $GIT_COMMIT           |

          EOF

          cat >> "$REPORT" << EOF

          ## Distributed package

          | Verified         | ${STATUS_DIST:-fail} |
          |------------------|----------------------|
          | Package checksum | $DEB_SHA256          |
          | Package URL      | [$DEB_URL]($DEB_URL) |
          EOF

          tee -a $GITHUB_STEP_SUMMARY >&2 < "$REPORT"

          [[ "$STATUS_REPRO" == "pass" ]]
          [[ "$STATUS_DIST" == "pass" ]]
