name: "[Verify package - plain]"

on:
  workflow_call:
    inputs:
      git-repo:
        description: "Git repository containing the package source(s)"
        required: true
        type: string
      git-ref:
        description: "Git reference"
        required: true
        type: string        
      package-name:
        description: "Package name (optional)"
        required: false
        default: ''
        type: string        

defaults:
  run:
    shell: bash

jobs:

  prep:
    runs-on: ubuntu-latest

    outputs:
      source-artifact: ${{ steps.source.outputs.name }}
      git-commit: ${{ steps.source.outputs.git-commit }}
      context: ${{ steps.context.outputs.json }}

    steps:
      - id: source
        name: Obtain source archive, extract local copy
        uses: disputechalice/actions/git-archive@main
        with:
          base-name: source
          git-repo: ${{ inputs.git-repo }}
          git-ref: ${{ inputs.git-ref }}
          extract: true

      - id: context
        name: Resolve context from .buildmeta file
        uses: disputechalice/actions/context-from-buildmeta@main
        with:
          source-dir: ${{ steps.source.outputs.extract-path }}

  repro:
    needs: prep
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.verify.outputs.status }}

    steps:
      - id: source
        name: Get package source
        uses: disputechalice/actions/fetch-archive@main
        with:
          name: ${{ needs.prep.outputs.source-artifact }}

      - id: verify
        name: Build verification
        uses: disputechalice/actions/repro-build@main
        with:
          image: ghcr.io/disputechalice/builder-plain:latest
          source-dir: ${{ steps.source.outputs.extract-path }}
          context: ${{ needs.prep.outputs.context }}

  dist:
    needs: prep
    runs-on: ubuntu-latest

    env:
      DEB_PACKAGE: ${{ fromJson(needs.prep.outputs.context).deb.package }}
      DEB_VERSION: ${{ fromJson(needs.prep.outputs.context).deb.version }}
      DEB_SHA256: ${{ fromJson(needs.prep.outputs.context).deb.sha256 }}
      DEB_URL: ${{ fromJson(needs.prep.outputs.context).deb.url }}

    outputs:
      status: ${{ steps.verify.outputs.status }}

    steps:
      - id: verify
        name: Verify distribution integrity
        run: |
          # Retrieve released package, i.a. verify checksum: ...
          # - confirm correct name/version
          # - verify retrieved package checksum as expected

          trap 'echo >&2 E$? L$LINENO' ERR
          : "${DEB_PACKAGE:?} ${DEB_VERSION:?} ${DEB_SHA256:?} ${DEB_URL:?}"

          dist_deb=$(mktemp /tmp/dist.XXXXXX.deb)
          wget --no-verbose -O "$dist_deb" "$DEB_URL"

          dist="$(dpkg-deb --show --showformat='${Package}|${Version}' "$dist_deb")"
          [[ "$dist" == "$DEB_PACKAGE|$DEB_VERSION" ]]

          sha256sum --check <<< "$DEB_SHA256  $dist_deb"

          >&2 tee -a "$GITHUB_OUTPUT" << EOF
          status=pass
          EOF

  report:
    needs: [prep, repro, dist]
    runs-on: ubuntu-latest

    env:
      GIT_URL: ${{ inputs.git-repo }}
      GIT_COMMIT: ${{ needs.prep.outputs.git-commit }}
      DEB_PACKAGE: ${{ fromJson(needs.prep.outputs.context).deb.package }}
      DEB_VERSION: ${{ fromJson(needs.prep.outputs.context).deb.version }}
      DEB_URL: ${{ fromJson(needs.prep.outputs.context).deb.url }}
      DEB_SHA256: ${{ fromJson(needs.prep.outputs.context).deb.sha256 }}
      STATUS_REPRO: ${{ needs.repro.outputs.status }}
      STATUS_DIST: ${{ needs.dist.outputs.status }}

    steps:
      - name: Report summary
        run: |
          # Build markdown summary, fail overall on any single fail

          trap 'echo >&2 E$? L$LINENO' ERR
          : "${GIT_URL:?} ${GIT_COMMIT:?}"           
          : "${DEB_PACKAGE:?} ${DEB_VERSION:?} ${DEB_URL:?} ${DEB_SHA256:?}"

          REPORT="$(mktemp --tmpdir --suffix=.md report.XXXXXX)"

          cat >> "$REPORT" << EOF
          **Report** as of: **$(date --rfc-3339=seconds --utc)**

          | Package | *$DEB_PACKAGE* |
          |---------|----------------|
          | Version | *$DEB_VERSION* |

          ## Reproducible build

          | Verified              | ${STATUS_REPRO:-fail} |
          |-----------------------|-----------------------|
          | Package checksum      | $DEB_SHA256           |          
          | Source Git repository | [$GIT_URL]($GIT_URL)  |
          | Source Git commit     | $GIT_COMMIT           |

          ## Distributed package

          | Verified         | ${STATUS_DIST:-fail} |
          |------------------|----------------------|
          | Package checksum | $DEB_SHA256          |
          | Package URL      | [$DEB_URL]($DEB_URL) |
          EOF

          >&2 tee -a "$GITHUB_STEP_SUMMARY" < "$REPORT"

          [[ "$STATUS_REPRO" == "pass" ]]
          [[ "$STATUS_DIST" == "pass" ]]
