name: "[Verify package]"

on:
  workflow_call:
    inputs:
      git-repo:
        description: "Git repository containing the package source(s)"
        required: true
        type: string
      git-ref:
        description: "Git reference"
        required: true
        type: string        
      package-name:
        description: "Package name (optional)"
        required: false
        default: ''
        type: string        

defaults:
  run:
    shell: bash

jobs:

  prep:
    runs-on: ubuntu-latest

    outputs:
      source-artifact: ${{ steps.source.outputs.name }}
      git-commit: ${{ steps.source.outputs.git-commit }}
      context: ${{ steps.context.outputs.json }}

    steps:

      - id: tester
        uses: disputechalice/actions/tester@main

      - id: source
        name: Obtain source archive, extract local copy
        uses: disputechalice/actions/git-archive@main
        with:
          base-name: source
          git-repo: ${{ inputs.git-repo }}
          git-ref: ${{ inputs.git-ref }}
          extract: true

      - id: context
        name: Resolve context from .buildmeta file
        uses: disputechalice/actions/context-from-buildmeta@main
        with:
          source-dir: ${{ steps.source.outputs.extract-path }}

  repro:
    needs: prep
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.verify.outputs.status }}

    steps:
      - id: source
        name: Get package source
        uses: disputechalice/actions/fetch-archive@main
        with:
          name: ${{ needs.prep.outputs.source-artifact }}

      - id: verify
        name: Verify reproducible build
        uses: disputechalice/actions/verify-build@main
        with:
          builder-image: ghcr.io/disputechalice/builder-plain:latest
          build-script: build-plain
          source-dir: ${{ steps.source.outputs.extract-path }}
          context: ${{ needs.prep.outputs.context }}

  dist:
    needs: prep
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.verify.outputs.status }}

    steps:
      - id: verify
        name: Verify distribution integrity
        uses: disputechalice/actions/verify-dist@main
        with:
          context: ${{ needs.prep.outputs.context }}

  report:
    needs: [prep, repro, dist]
    runs-on: ubuntu-latest

    env:
      R_REPRO: ${{ needs.repro.result }}
      R_DIST: ${{ needs.dist.result }}

      GIT_URL: ${{ inputs.git-repo }}
      GIT_COMMIT: ${{ needs.prep.outputs.git-commit }}
      DEB_PACKAGE: ${{ fromJson(needs.prep.outputs.context).deb.package }}
      DEB_VERSION: ${{ fromJson(needs.prep.outputs.context).deb.version }}
      DEB_SHA256: ${{ fromJson(needs.prep.outputs.context).deb.sha256 }}
      DEB_URL: ${{ fromJson(needs.prep.outputs.context).deb.url }}

    steps:
      - name: Report summary
        run: |
          # Build markdown summary, fail overall on any single fail

          trap 'echo >&2 E$? L$LINENO' ERR
          : "${GIT_URL:?} ${GIT_COMMIT:?}"           
          : "${DEB_PACKAGE:?} ${DEB_VERSION:?} ${DEB_URL:?} ${DEB_SHA256:?}"

          REPORT="$(mktemp --tmpdir --suffix=.md report.XXXXXX)"

          cat >> "$REPORT" << EOF
          **Report** as of: **$(date --rfc-3339=seconds --utc)**

          | Package | *$DEB_PACKAGE* |
          |---------|----------------|
          | Version | *$DEB_VERSION* |

          ## Reproducible build

          | Verification          | $R_REPRO             |
          |-----------------------|----------------------|
          | Package checksum      | $DEB_SHA256          |          
          | Source Git repository | [$GIT_URL]($GIT_URL) |
          | Source Git commit     | $GIT_COMMIT          |

          ## Distributed package

          | Verification     | $R_DIST              |
          |------------------|----------------------|
          | Package checksum | $DEB_SHA256          |
          | Package URL      | [$DEB_URL]($DEB_URL) |
          EOF

          >&2 tee -a "$GITHUB_STEP_SUMMARY" < "$REPORT"

          [[ "$R_REPRO" == "success" ]]
          [[ "$R_DIST" == "success" ]]
