name: build builder

on:
  workflow_call:
    inputs:
      def_repo:
        required: true
        type: string
      def_ref:
        required: false
        type: string
        default: main
      image_name:
        required: false
        type: string
        default: builder-simple
      image_tag:
        required: false
        type: string
        default: latest

env:
  IMAGE: ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}
  TAG: ${{ inputs.image_tag }}
  SOURCE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  AUTHORS: ${{ github.repository_owner }}
  DESCRIPTION: Builder image
  BOOTSTRAP: def/builder/bootstrap.yaml
  SOURCE_DATE_EPOCH: 1775941938

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    secrets: inherit      
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout def
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.def_repo }}
          ref: ${{ inputs.def_ref }}
          path: def

      - name: Prep environment
        run: |
          export APT_CONFIG=$(realpath def/builder/apt.conf)
          export DEBIAN_FRONTEND=noninteractive

          sudo -E apt-get update
          sudo -E apt-get satisfy \
            debian-archive-keyring \
            bdebstrap \
            buildah \
            podman

      - id: build
        name: Build image
        run: |
          export SOURCE_DATE_EPOCH BOOTSTRAP IMAGE TAG SOURCE AUTHORS DESCRIPTION

          buildah unshare def/builder/build

          cat >> $GITHUB_OUTPUT << EOF
          rootfs-diffid-0=$(buildah inspect "$IMAGE:$TAG" | jq -r '.OCIv1.rootfs.diff_ids[0]')
          EOF

      - name: Check image
        run: |
          source <(podman run --pull=never "$IMAGE:$TAG" cat /etc/os-release)
          [[ $ID == debian ]]

      - id: push
        name: Push to Registry
        run: |
          buildah login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"

          buildah push \
            --digestfile digest \
            "$IMAGE:$TAG"

          cat >> $GITHUB_OUTPUT << EOF
          image-digest=$(cat digest)
          EOF

      - name: Summarize
        env:
          ROOTFS_DIFFID0: ${{ steps.build.outputs.rootfs-diffid-0 }}
          IMAGE_DIGEST: ${{ steps.push.outputs.image-digest }}

        run: |
          # Build markdown summary
          trap 'echo >&2 E$? L$LINENO' ERR
          : "${IMAGE_DIGEST:?}"

          tee -a "report.md" >&2 << EOF
          $IMAGE : $TAG

          rootfs diffid 0: $ROOTFS_DIFFID0

          pushed image: $IMAGE_DIGEST

          \`\`\`
          $(yq '.mmdebstrap.suite' "$BOOTSTRAP")
          $(yq '.mmdebstrap.variant' "$BOOTSTRAP")
          $(yq '.mmdebstrap.mirrors' "$BOOTSTRAP")          
          \`\`\`
          EOF

          cat report.md >> $GITHUB_STEP_SUMMARY
