name: Build builder-plain

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-builder.yaml
    with:
      def-repo: disputechalice/builder
      def-ref: main
      def-name: plain
      image-tag: latest
