name: Build builder-plain

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-builder.yml
    with:
      def_repo: disputechalice/builder
      def_ref: main
      image_name: builder-simple
      image_tag: latest
