name: build builder from definition

on:
  workflow_call:
    inputs:
      def-repo:
        required: true
        type: string
      def-ref:
        required: false
        type: string
        default: main
      def-name:
        required: true
        type: string
      image-tag:
        required: false
        type: string
        default: latest

defaults:
  run:
    shell: bash

env:
  GIT_URL: ${{ inputs.def-repo }}
  GIT_REF: ${{ inputs.def-ref }}
  BUILD_SCRIPT: def/${{ inputs.def-name }}/build
  BOOTSTRAP_YAML: def/${{ inputs.def-name }}/bootstrap.yaml
  IMAGE: ghcr.io/${{ github.repository_owner }}/builder-${{ inputs.def-name }}
  IMAGE_TAG: ${{ inputs.image-tag }}

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Prep runner toolset
        uses: disputechalice/test-gh-actions/apt-satisfy@main
        with:
          expression: >
            debian-archive-keyring
            bdebstrap
            buildah
            podman

      - id: def
        name: Fetch def tree
        uses: disputechalice/test-gh-actions/tree-from-gitref@main
        with:
          git-url: ${{ env.GIT_URL }}
          git-ref: ${{ env.GIT_REF }}
          target: def

      - id: build
        name: Build image
        env:
          SOURCE_DATE_EPOCH: ${{ steps.def.outputs.git-commit-epoch }}
          IMAGE_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          IMAGE_SOURCE: ${{ inputs.def-repo }}
          IMAGE_REVISION: ${{ steps.def.outputs.git-commit }}
          IMAGE_AUTHORS: ${{ github.repository_owner }}
          IMAGE_DESCRIPTION: Builder-${{ inputs.def-name }}

        run: |
          export SOURCE_DATE_EPOCH IMAGE IMAGE_{TAG,URL,SOURCE,REVISION,AUTHORS,DESCRIPTION}

          buildah unshare "$BUILD_SCRIPT"

          cat >> $GITHUB_OUTPUT << EOF
          rootfs-diffid-0=$(buildah inspect "$IMAGE:$IMAGE_TAG" | jq -r '.OCIv1.rootfs.diff_ids[0]')
          EOF

      - name: Check image
        run: |
          source <(podman run --pull=never "$IMAGE:$IMAGE_TAG" cat /etc/os-release)
          [[ $ID == debian ]]

      - id: push
        name: Push to Registry
        run: |
          buildah login ghcr.io \
            -u "${{ github.actor }}" \
            --password-stdin <<< "${{ secrets.GITHUB_TOKEN }}"

          buildah push \
            --digestfile digest \
            "$IMAGE:$IMAGE_TAG"

          cat >> $GITHUB_OUTPUT << EOF
          image-digest=$(cat digest)
          EOF

      - name: Summarize
        env:
          ROOTFS_DIFFID0: ${{ steps.build.outputs.rootfs-diffid-0 }}
          IMAGE_DIGEST: ${{ steps.push.outputs.image-digest }}
          GIT_COMMIT: ${{ steps.def.outputs.git-commit }}
          TAR_SHA256: ${{ steps.def.outputs.tar-sha256 }}
        run: |
          # Build markdown summary
          trap 'echo >&2 E$? L$LINENO' ERR
          : "${IMAGE_DIGEST:?}"

          tee -a "report.md" >&2 << EOF
          $IMAGE : $IMAGE_TAG

          rootfs diffid 0: $ROOTFS_DIFFID0

          pushed image: $IMAGE_DIGEST

          \`\`\`
          $(yq '.mmdebstrap.suite' "$BOOTSTRAP_YAML")
          $(yq '.mmdebstrap.variant' "$BOOTSTRAP_YAML")
          $(yq '.mmdebstrap.mirrors' "$BOOTSTRAP_YAML")          
          \`\`\`

          Image def:
          - from commit $GIT_COMMIT
          - tarball SHA256: $TAR_SHA256
          EOF

          cat report.md >> $GITHUB_STEP_SUMMARY
