name: Build builder-plain

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/build-builder.yaml
    with:
      def_repo: disputechalice/builder
      def_ref: main
      image_name: builder-simple
      image_tag: latest
