name: Build builder-plain

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-builder.yaml
    with:
      def-repo: https://github.com/disputechalice/builder.git
      def-ref: main
      def-name: plain
      image-tag: latest
