name: Build builder image - plain

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-image.yaml
    with:
      git-repo: https://github.com/disputechalice/builder.git
      git-ref: main
      def-name: plain
      image-name: builder-plain
      image-tag: latest
