name: Build images

on:
  workflow_dispatch:

jobs:
  builder-plain:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/_build-image.yaml
    with:
      git-repo: https://github.com/disputechalice/builder.git
      git-ref: main
      def-name: plain
      image-name: builder-plain
      image-tags: "latest run-${{ github.run_id }}"
