name: Verify package - no-subscription
on:
  workflow_dispatch:

jobs:
  no-subscription:
    uses: ./.github/workflows/_verify-package_plain-hermetic.yaml
    with:
      git-repo: https://github.com/free-pmx/free-pmx-no-subscription.git
      git-ref: main
