name: Verify package - no-subscription
on:
  workflow_dispatch:

jobs:
  tester:
    uses: disputechalice/actions/tester@main
  no-subscription:
    uses: ./.github/workflows/_verify-package.yaml
    with:
      git-repo: https://github.com/free-pmx/free-pmx-no-subscription.git
      git-ref: main
